views/home.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, current_app, abort
from werkzeug.utils import secure_filename
import time
import json
import ConfigParser
from StringIO import StringIO
import os 
import random

from models.messages import PostForm 
from decorator import login_required
from lib import s3
from lib.database import db
from lib import form
from lib import pagination

flash_config = ConfigParser.ConfigParser()
flash_config.read('config/flash.cfg')

database = db()
database.init_db()

home_blueprint = Blueprint('home', __name__, template_folder='templates', static_folder='static')
msgs_in_each_page = pagination.msgs_in_each_page


html_escape_table = {
     "&": "&amp;",
     '"': "&quot;",
     "'": "&apos;",
     ">": "&gt;",
     "<": "&lt;",
     }

def html_escape(text):
     return "".join(html_escape_table.get(c,c) for c in text)


@home_blueprint.route("/home/")
@home_blueprint.route("/home")
@login_required
def home():
    postform = PostForm()
    total_pages = len(database.get_msg_list())/msgs_in_each_page+1
    return render_template('home.html', form=postform, total_pages=total_pages)

@home_blueprint.route("/home/<request_page>")
@login_required
def page(request_page):
    try:
        message_list_by_id = pagination.get_page(request_page, session['logged_in'])
    except ValueError as ex:
        current_app.logger.error('request_page is not number')
        abort(404)

    if 'error' in message_list_by_id:
        flash(flash_config.get('home', 'page_not_exist'))
        return render_template('404.html')

    messages = []
    if message_list_by_id:
        for mid in message_list_by_id:
            message = database.get_msg_by_id(mid)
            if message['user'].split(':')[0] == 'google':
                message['user'] = message['user'].split(':')[2]
            messages.append(message)
            if 'image' in message:
                message['image_data'] = s3.s3_get(message['image'])
    return json.dumps(messages) 

@home_blueprint.route("/pomsg", methods=['POST'])
@login_required
def pomsg():
    postform = PostForm(request.form)
    if request.method == 'POST' and postform.validate():
        ori_last_mid = database.get_latest_mid()
        message ={  'mid': str(ori_last_mid+1),
                    'time': time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())),
                    'user': session['logged_in'], 
                    'message': html_escape(postform.message.data) }
        if request.files[postform.upload.name]:
            image = request.files[postform.upload.name]
            pos = image.tell()
            file_length = len(image.read())
            image.seek(pos)
            if file_length < (2 * 1024 * 1024):
                if image.content_type.startswith('image/'):
                    filename = session['logged_in'] + ':' + str(ori_last_mid+1) + ':' + secure_filename(image.filename)
                    s3.s3_put(filename, image)
                    message['image'] = filename
                    image.close()
                else:
                    current_app.logger.warn(str(session['logged_in'])+' upload file-content error')
                    flash(flash_config.get('home', 'upload_file_type_error'))
                    image.close()
                    return redirect(url_for('home.home'))
            else:
                current_app.logger.warn(str(session['logged_in'])+' upload file too big')
                flash(flash_config.get('home', 'upload_file_too_big'))
                image.close()
                return redirect(url_for('home.home'))
        try:
            database.add_msg(str(ori_last_mid+1), session['logged_in'], message)
        except:
            current_app.logger.error('add message fail')
    elif request.method == 'POST' and not postform.validate():
        form.flash_errors(postform)
    return redirect(url_for('home.home'))

@home_blueprint.route("/delmsg/<mid>", methods=['GET'])
@login_required
def delmsg(mid):
    if request.method == 'GET':
        try:
            message = database.get_msg_by_id(mid)
            if message['user'] == session['logged_in']:
                if 'image' in message:
                    s3.s3_delete(message['image'])
                database.del_msg(mid, session['logged_in'])
            else:
                current_app.logger.warn(str(session['logged_in'])+' try to delete illegal message')
            flash (flash_config.get('home', 'delmsg_success'))
            return redirect(url_for('home.home'))
        except TypeError as ex:
            abort(403)

views/index.py
from flask import Blueprint, render_template, flash, current_app, abort
import json
import ConfigParser

from lib import s3
from lib.database import db
from lib import pagination

flash_config = ConfigParser.ConfigParser()
flash_config.read('config/flash.cfg')

database = db()
database.init_db()

index_blueprint = Blueprint('index', __name__, template_folder='templates', static_folder='static')
msgs_in_each_page = pagination.msgs_in_each_page

@index_blueprint.route("/")
def index():
    total_pages = len(database.get_msg_list())/msgs_in_each_page+1
    return render_template('index.html', total_pages=total_pages)

@index_blueprint.route("/<request_page>")
def page(request_page):
    try:
        message_list = pagination.get_page(request_page)
    except ValueError as ex:
        current_app.logger.error('request_page is not number')
        abort(404)

    if 'error' in message_list:
        flash(flash_config.get('index', 'page_not_exist'))
        return render_template('404.html')

    messages = []
    if message_list:
        for mid in message_list:
            message = database.get_msg_by_id(mid)
            if 'google' in message['user']:
                if message['user'].split(':')[0] == 'google':
                    message['user'] = message['user'].split(':')[2] 
            if 'image' in message:
                message['image_data'] = s3.s3_get(message['image'])
            messages.append(message)
    return json.dumps(messages)

views/login.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
import hashlib
import time
import ConfigParser

from models.users import LoginForm
from decorator import login_not_required
from lib.database import db
from lib import form
from lib import google_openid

flash_config = ConfigParser.ConfigParser()
flash_config.read('config/flash.cfg')

database = db()
database.init_db()

login_blueprint = Blueprint('login', __name__, template_folder='templates', static_folder='static')

@login_blueprint.route("/google_login")
def google_login():
    auth_uri = google_openid.flow_step_1()
    return redirect(auth_uri)

@login_blueprint.route("/oauth2cb")
def oauth2cb():
    if 'code' in request.args:
        goog_user_id, user_given_name, goog_user_avatar = google_openid.flow_step_2(request.args['code'])
        if goog_user_id == user_given_name == goog_user_avatar == 'fail':
            flash(flash_config.get('login', 'openid_error'))
            return redirect(url_for('login.login'))
        # if you haven't login, add user
        if database.get_user_by_username('google:'+goog_user_id+':'+user_given_name) == None:
            ori_last_uid = database.get_latest_uid()
            username = 'google:'+goog_user_id+':'+user_given_name
            user_info = { 'uid':ori_last_uid+1,
                         'goog_user_id':goog_user_id,
                         'goog_user_avatar': goog_user_avatar,
                         'username':user_given_name,
                         'regtime': time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())) }
            database.add_user(str(ori_last_uid+1), username, user_info)
        flash(flash_config.get('login', 'login_success'))
        session['logged_in'] = 'google:'+goog_user_id+':'+user_given_name 
        session['avatar'] = goog_user_avatar
        return redirect(url_for('home.home'))
    else:
        flash(flash_config.get('login', 'login_fail'))
        return redirect(url_for('login.login'))

@login_blueprint.route("/login")
@login_not_required
def login():
    form = LoginForm()
    return render_template('login.html', form=form) 

@login_blueprint.route("/verify_login", methods=['POST'])
@login_not_required
def verify_login():
    loginform = LoginForm(request.form)
    if request.method == 'POST' and loginform.validate():
        if database.get_user_by_username(loginform.username.data):
            login_user = database.get_user_by_username(loginform.username.data)
            if login_user['password'] == hashlib.sha224(loginform.password.data).hexdigest():
                flash(flash_config.get('login', 'login_success'))
                session['logged_in'] = loginform.username.data
                return redirect(url_for('home.home'))
            else:
                flash(flash_config.get('login', 'wrong_password'))
        else:
            flash(flash_config.get('login', 'no_such_user'))
    elif request.method == 'POST' and not loginform.validate():
        form.flash_errors(loginform) 
    return render_template('login.html', form = loginform) 

@login_blueprint.route("/logout")
def logout():
    session.clear()
    flash(flash_config.get('login', 'logout_success'))
    return redirect(url_for('index.index'))

views/profile.py
from flask import Blueprint, render_template, session, current_app, abort

from decorator import login_required
from lib.database import db

database = db()
database.init_db()

profile_blueprint = Blueprint('profile', __name__, template_folder='templates', static_folder='static')

@profile_blueprint.route('/profile')
@login_required
def profile():
    try:
        profile_info = database.get_user_by_username(session['logged_in'])
        profile_info.pop('password', None)
    except AttributeError as ex:
        current_app.logger.error('Something wrong while getting user from database') 
        abort(500)
    return render_template('profile.html', profile_info=profile_info)

views/register.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, current_app, abort
import hashlib
import time
import ConfigParser

from models.users import RegistrationForm
from decorator import login_not_required
from lib.database import db
from lib import form

key_config = ConfigParser.ConfigParser()
key_config.read('config/key.cfg')
flash_config = ConfigParser.ConfigParser()
flash_config.read('config/flash.cfg')

database = db()
database.init_db()

register_blueprint = Blueprint('register', __name__, template_folder='templates', static_folder='static')

@register_blueprint.route("/register")
@login_not_required
def register():
    form = RegistrationForm()
    return render_template('register.html', form=form)

@register_blueprint.route("/verify_register", methods=['POST'])
@login_not_required
def verify_register():
    registform = RegistrationForm(request.form, captcha={'ip_address': request.remote_addr})
    form_validator = registform.validate()

    if unicode(key_config.get('test_only', 'captcha_allow')) == registform.password.data:
        form_validator = True

    if request.method == 'POST' and form_validator and ':' not in registform.username.data:
        try:
            if database.get_user_by_username(registform.username.data) == None:
                if registform.password.data == registform.confirm_password.data:
                    ori_last_uid = database.get_latest_uid()
                    user_info = { 'uid':ori_last_uid+1,
                                  'username':registform.username.data,
                                  'password':hashlib.sha224(registform.password.data).hexdigest(),
                                  'regtime':time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))}
                    database.add_user(str(ori_last_uid+1), registform.username.data, user_info)
                    flash(flash_config.get('register', 'register_success'))
                    session['logged_in'] = registform.username.data
                    return redirect(url_for('home.home'))
                else:
                    flash(flash_config.get('register', 'password_not_match'))
                    return redirect(url_for('register.register'))
            else:
                flash(flash_config.get('register', 'user_exist'))
                return redirect(url_for('register.register'))
        except:
            current_app.logger.error('Something wrong in user database')
            abort(500)
    else:
        form.flash_errors(registform)
        return render_template('register.html', form=registform)

templates/home.html
{% extends "layout.html" %}
{% block body %}
<script type="text/javascript">
function get_code(msg)
{
    var code;
    code =  '<div id=\"' + msg['mid'] +'\" class=\"panel-group\">' +
            '    <div class=\"panel panel-success\">' +
            '        <div class=\"panel-heading\">';
    if ('avatar' in msg)
    code += '            <img src=\"'+ msg['avatar']+'\" height=\"25\" width=\"25\"/>';
    code +=              msg['user'] + ' @ ' + msg['time'] + 
            '            <button type=\"button\" id=\"del\" class=\"btn btn-link btn-xsm\">' +
            '            <a href=\"/delmsg/'+msg['mid']+'\" method=get style=\"text-decoration:none; color:green\">delete</a>' +
            '            </button>' +
            '        </div>' + 
            '        <div class=\"panel-body\">'+msg['message']+'</div>';
    if ('image_data' in msg)
    code += '        <img src=\"data:image;base64,'+msg['image_data']+'\" />';
    code += '    </div>' +
            '    <hr/>' +
            '</div>';
    return code;
}
$(document).ready(function() {
	$('#upload').bind('change', function() {
		if (this.files[0].size > 2*1024*1024){
			alert('upload file size should not greater than 2MB');
			$('#upload').val('');
		}	
	});
    var current_page = 1;
    var loading = false;
    var total_pages = {{total_pages}};
    $.getJSON("{{url_for('home.page', request_page=1 )}}", function(msgs){
        for (var key=0; key<msgs.length; key++)
            $('#results').append(get_code(msgs[key]));
    });
    $(window).scroll(function() {
        if($(window).scrollTop() + $(window).height() > $(document).height()*99/100) 
        {
            if (current_page <= total_pages+1 && loading == false)
            {
                loading=true;
                current_page++;
                $('.animation_image').show();
                $.getJSON("/home/"+current_page, function(msgs){
                    for (var key=0; key<msgs.length; key++)
                        $('#results').append(get_code(msgs[key]));
                    loading=false;
                }).fail(function(xhr, ajaxOptions, thrownError) {
                    loading = false;
                });
            }
        }
        if (loading == false)
            $('.animation_image').hide();
    });
});
</script>
{% if session.logged_in %}
    <form role="form" action="{{ url_for('home.pomsg') }}" method=post enctype=multipart/form-data >
        <div class="form-group">
            {{ form.message(class="form-control", id="message") }}
            {{ form.upload(class="form-control", id="upload") }}
            {{ form.submit(class="btn btn-link", style="color:green") }}
        </div>
    </form>
    <div id="results">
    </div>
    <div class="animation_image" style="display:none" align="center">
        <img width="10%" height="10%" src="../static/img/ajax_loader.gif"/>
    </div>
{% endif %}
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block body %}
<script type="text/javascript">
function get_code(msg)
{
    var code;
    code =  '<div id=\"' + msg['mid'] +'\" class=\"panel-group\">' +
            '    <div class=\"panel panel-success\">' +
            '        <div class=\"panel-heading\">';
    if ('avatar' in msg)
    code += '            <img src=\"'+ msg['avatar']+'\" height=\"25\" width=\"25\"/>';
    code +=              msg['user'] + ' @ ' + msg['time'] + 
            '        </div>' + 
            '        <div class=\"panel-body\">'+msg['message']+'</div>';
    if ('image_data' in msg)
    code += '        <img src=\"data:image;base64,'+msg['image_data']+'\" />';
    code += '    </div>' +
            '    <hr/>' +
            '</div>';
    return code;
}
$(document).ready(function() {
    var current_page = 1;
    var loading = false;
    var total_pages = {{total_pages}};
    $.getJSON("{{url_for('index.page', request_page=1 )}}", function(msgs){
        for (var key=0; key<msgs.length; key++)
            $('#results').append(get_code(msgs[key]));
    });
    $(window).scroll(function() {
        if($(window).scrollTop() + $(window).height() > $(document).height()*99/100) 
        {
            if (current_page <= total_pages && loading == false)
            {
                loading=true;
                current_page++;
                $('.animation_image').show();
                $.getJSON("/"+current_page, function(msgs){
                    for (var key=0; key<msgs.length; key++)
                        $('#results').append(get_code(msgs[key]));
                    loading=false;
                }).fail(function(xhr, ajaxOptions, thrownError) {
                    loading = false;
                });
            }
        }
        if (loading == false)
            $('.animation_image').hide();
    });
});
</script>
<div id="results">
</div>
<div class="animation_image" style="display:none" align="center">
    <img width="10%" height="10%" src="static/img/ajax_loader.gif"/>
</div>
{% endblock %}

templates/layout.html
<!doctype html>
<title>TC</title>
<link rel="icon" href="/static/favicon.ico" type="image/x-icon">
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<nav class="navbar navbar-inverse">
<div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="{{ url_for('index.index') }}">Welcome to TC</a>
    </div>
    <div>
        {% if not session.logged_in %}
        <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{{ url_for('login.login') }}">login</a></li>
            <li><a href="{{ url_for('register.register') }}">register</a></li>
        </ul>
        {% else %}
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('home.home') }}">home</a></li>
            <li><a href="{{ url_for('profile.profile') }}">profile</a></li>        
        </ul>
        <ul class="nav navbar-nav navbar-right">
              <li><a href="{{ url_for('login.logout') }}">logout</a></li>
        </ul>
        {% endif %}
        </ul>
    </div>
</div>
</nav>
{% for message in get_flashed_messages() %}
    <div class="alert alert-danger" data-offset="50"><strong>{{ message }}</strong></div>
{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<div class=container>
{% block body %}
{% endblock %}
</div>

templates/login.html
{% extends "layout.html" %}
{% block body %}
<h2>login</h2>
{% if not session.logged_in %}
<form role="form" action="{{ url_for('login.verify_login') }}" method=post>
    <div class="form-group"> 
        <label for="username">{{ form.username.label }}</label> 
        {% if form.username.data %}
            {{ form.username(class="form-control", id="username", value=form.username.data) }}
        {% else %}
            {{ form.username(class="form-control", id="username") }}
        {% endif %}
        <label for="password">{{ form.password.label }}</label> 
        {{ form.password(class="form-control", id="password") }}
        {{ form.submit(value="login", class="btn btn-link", style="color:green") }}
        <button class="btn btn-link">
            <a href="{{ url_for('register.register') }}" style="text-decoration:none; color:green">register</a>
        </button>
        <hr/>
        <button class="btn btn-link">
            <a href="{{ url_for('login.google_login') }}" style="text-decoration:none; color:green">login with google</a>
        </button>         
    </div>
</form>
{% endif %}
{% endblock %}

templates/profile.html
{% extends "layout.html" %}
{% block body %}
<script>
$(window).load(function(){
    $("img").each(function(i){
        if($(this).attr("alumb")=="true"){
            $(this).removeAttr('width');
            $(this).removeAttr('height');
            var imgW = $(this).width();
            var imgH = $(this).height();
            var w=$(this).attr("_w")/imgW;
            var h=$(this).attr("_h")/imgH;
            var pre=1;
            if(w>h){pre=h;}
            else{pre=w;}
            $(this).width(imgW*pre);
            $(this).height(imgH*pre);
        }
    });
});
</script>

<div class="container">
    <div class="panel panel-default" align="center">
        <img src="{{ session.avatar }}" alumb="true" _w="100" _h="100" width="360"/>
    </div>
    <table class="table">
        <tbody>
            <tr class="success">
                <th>username</th>
                <td>{{ profile_info.username }}</td>
            </tr>
            <tr>
                <th>uid</th>
                <td>{{ profile_info.uid }}</td>
            </tr>
            <tr>
                <th>since</th>
                <td>{{ profile_info.regtime }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<script type="text/javascript">
$(document).ready(function() { 
	$('#password').keyup(function(e) {
		var marvelRegex = new RegExp("^(?=.{16,})((?=.*[a-z])(?=.*[0-9)(?=.*[A-Z]))(?=.*[~!@#$%^&*()_+]).*$", "g");
		var strongRegex = new RegExp("^(?=.{10,})((?=.*[a-z])(?=.*[0-9)(?=.*[A-Z]))(?=.*[~!@#$%^&*()_+]).*$", "g");
		var mediumRegex = new RegExp("^(?=.{8,})((?=.*[a-z])(?=.*[0-9)(?=.*[A-Z])).*$", "g");
		var okokokRegex = new RegExp("^(?=.{6,})((?=.*[a-z])((?=.*[0-9])|(?=.*[A-Z]))).*$", "g");
		var enoughRegex = new RegExp("(?=.{1,}).*", "g");
		if (false == enoughRegex.test($(this).val())) {
			 $('#passstrength').html('');
		} else if (marvelRegex.test($(this).val())) {
			 $('#passstrength').html('Oh my god, this password is so amazing!');
		} else if (strongRegex.test($(this).val())) {
			 $('#passstrength').html('Very strong!');
		} else if (mediumRegex.test($(this).val())) {
			 $('#passstrength').html('Seems ok!');
		} else if (okokokRegex.test($(this).val())) {
			 $('#passstrength').html('Well, not bad!');
		} else {
			 $('#passstrength').html('So bad!');
		}
		return true;
	})
})
</script>
<style type="text/css">
#passstrength {
	color:green;
	font-family:verdana;
	font-size:10px;
	font-weight:bold;
}
</style>
<h2>Register</h2>
{% if not session.logged_in %}
<form role="form" action="{{ url_for('register.verify_register') }}" method=post>
        <label for="username">{{ form.username.label }}</label>
        {% if form.username.data %}
            {{ form.username(class="form-control", id="username", value=form.username.data) }}
        {% else %}
            {{ form.username(class="form-control", id="username") }}
        {% endif %}
        <label for="password">{{ form.password.label }}</label>
		<span id="passstrength"></span>
        {{ form.password(class="form-control", id="password") }}
        <label for="confirm_password">{{ form.confirm_password.label }}</label>
        {{ form.confirm_password(class="form-control", id="confirm_password") }}
		<label for="recaptcha">{{ form.captcha.label }}</label>
		<div class="g-recaptcha" data-sitekey="6LeeJRETAAAAAFhkaZ83JnEH0yaHIDFzgZziqP56">
			{% if form.captcha.short_name == "captcha" %}
				{{ form.captcha(class="form-control") | safe }}
			{% else %}
				{{ form.captcha(class="form-control") }}
			{% endif %}
		</div>
        {{ form.submit(value="register", class="btn btn-link", style="color:green") }}
    </div>
</form>
{% endif %}
{% endblock %}